# Generated by Django 3.1.6 on 2023-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=4)),
                ('event_name', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField()),
                ('organizer_email', models.CharField(max_length=50)),
                ('organizer_phone', models.CharField(max_length=10)),
                ('event_description', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('Virtual', 'Virtual'), ('On-Premise', 'On-Premise')], max_length=15)),
                ('event_location', models.CharField(max_length=20)),
                ('event_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('max_seats', models.CharField(max_length=5)),
            ],
        ),
    ]
