# Generated by Django 3.1.6 on 2023-02-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
