# Generated by Django 3.1.6 on 2023-02-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20230218_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Live', 'Live'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('On-Premise', 'On-Premise'), ('Virtual', 'Virtual')], max_length=15),
        ),
    ]
