# Generated by Django 3.1.6 on 2023-02-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20230218_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Live', 'Live'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_phone',
            field=models.CharField(max_length=10),
        ),
    ]
