# Generated by Django 3.1.6 on 2023-02-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20230218_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='booking_id',
            field=models.CharField(max_length=4),
        ),
    ]
