# Generated by Django 3.1.6 on 2023-02-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20230218_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=30)),
                ('participant_email', models.CharField(max_length=40)),
                ('participant_phone', models.IntegerField(max_length=10)),
                ('participant_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Live', 'Live'), ('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('On-Premise', 'On-Premise'), ('Virtual', 'Virtual')], max_length=15),
        ),
    ]
