# Generated by Django 3.1.6 on 2023-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20230218_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Live', 'Live'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('On-Premise', 'On-Premise')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participant_phone',
            field=models.IntegerField(),
        ),
    ]
